on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
      - semgrep_rule.yaml
      - bookshop.php

name: Semgrep

jobs:
  run-semgrep-custom-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep with custom rule
        run: semgrep --config=semgrep_rule.yaml bookshop.php
