on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
      - semgrep_rule.yaml
      - bookshop.php
  schedule:
    - cron: 33 1 * * *

name: Semgrep

jobs:
  semgrep:
    name: Custom Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Run custom Semgrep rule
        run: semgrep --config=semgrep_rule.yaml bookshop.php
